"""Default GlobalMarketUniverse — parameters are illustrative for roadmap stress tests, not live forecasts."""

from __future__ import annotations

from yanfu_global_expansion.universe_models import GlobalMarketUniverse, MarketMicrostructure


def build_default_universe() -> GlobalMarketUniverse:
    return GlobalMarketUniverse(
        markets={
            "CN_CSI1000": MarketMicrostructure(
                code="CN_CSI1000",
                name="China A-share CSI 1000 (T+1, retail-heavy)",
                settlement="T+1",
                retail_participation_pct=82.0,
                institutional_dominance_pct=18.0,
                annualized_vol_hint=0.28,
                impact_bps_per_million_notional=18.0,
                correlation_to_cn_alpha=1.0,
                momentum_reversal_alpha_transfer=1.0,
                notes="High impact, reversal/momentum pockets; Yanfu DNA baseline.",
            ),
            "CN_CSI500": MarketMicrostructure(
                code="CN_CSI500",
                name="China A-share CSI 500",
                settlement="T+1",
                retail_participation_pct=78.0,
                institutional_dominance_pct=22.0,
                annualized_vol_hint=0.24,
                impact_bps_per_million_notional=12.0,
                correlation_to_cn_alpha=0.92,
                momentum_reversal_alpha_transfer=0.88,
                notes="Slightly lower idiosyncratic vol versus CSI1000.",
            ),
            "HK_HSTECH": MarketMicrostructure(
                code="HK_HSTECH",
                name="Hang Seng Tech (T+0, CN-beta proxy)",
                settlement="T+0",
                retail_participation_pct=45.0,
                institutional_dominance_pct=55.0,
                annualized_vol_hint=0.32,
                impact_bps_per_million_notional=8.0,
                correlation_to_cn_alpha=0.72,
                momentum_reversal_alpha_transfer=0.55,
                notes="Southbound / ADR linkage; institutional mix.",
            ),
            "US_SP500": MarketMicrostructure(
                code="US_SP500",
                name="US S&P 500 sleeve (deep book)",
                settlement="T+0",
                retail_participation_pct=25.0,
                institutional_dominance_pct=75.0,
                annualized_vol_hint=0.16,
                impact_bps_per_million_notional=2.5,
                correlation_to_cn_alpha=0.18,
                momentum_reversal_alpha_transfer=0.22,
                notes="Low impact; quantamental / alternative alpha to compete.",
            ),
            "US_RUT2000": MarketMicrostructure(
                code="US_RUT2000",
                name="US Russell 2000 (capacity-constrained vs SPX)",
                settlement="T+0",
                retail_participation_pct=35.0,
                institutional_dominance_pct=65.0,
                annualized_vol_hint=0.24,
                impact_bps_per_million_notional=5.0,
                correlation_to_cn_alpha=0.28,
                momentum_reversal_alpha_transfer=0.42,
                notes="Closer to small-cap stat-arb heritage but still US microstructure.",
            ),
            "IN_NIFTY50": MarketMicrostructure(
                code="IN_NIFTY50",
                name="India Nifty 50",
                settlement="T+1",
                retail_participation_pct=72.0,
                institutional_dominance_pct=28.0,
                annualized_vol_hint=0.18,
                impact_bps_per_million_notional=14.0,
                correlation_to_cn_alpha=0.35,
                momentum_reversal_alpha_transfer=0.68,
                notes="High idiosyncratic vol pockets; partial A-share analogue.",
            ),
            "VN_VNI": MarketMicrostructure(
                code="VN_VNI",
                name="Vietnam VN-Index",
                settlement="T+2",
                retail_participation_pct=76.0,
                institutional_dominance_pct=24.0,
                annualized_vol_hint=0.22,
                impact_bps_per_million_notional=20.0,
                correlation_to_cn_alpha=0.40,
                momentum_reversal_alpha_transfer=0.75,
                notes="Retail-heavy, episodic liquidity.",
            ),
            "CRYPTO_ETF_IBIT": MarketMicrostructure(
                code="CRYPTO_ETF_IBIT",
                name="US-listed spot BTC ETF proxy (IBIT)",
                settlement="T+0",
                retail_participation_pct=60.0,
                institutional_dominance_pct=40.0,
                annualized_vol_hint=0.55,
                impact_bps_per_million_notional=4.0,
                correlation_to_cn_alpha=0.05,
                momentum_reversal_alpha_transfer=0.35,
                notes="24/7 spot; compliant ETF wrapper; mean-reversion satellite.",
            ),
            "CRYPTO_ETF_ETHW": MarketMicrostructure(
                code="CRYPTO_ETF_ETHW",
                name="US-listed ETH ETF proxy (e.g. ETHW / analogous)",
                settlement="T+0",
                retail_participation_pct=62.0,
                institutional_dominance_pct=38.0,
                annualized_vol_hint=0.62,
                impact_bps_per_million_notional=4.5,
                correlation_to_cn_alpha=0.06,
                momentum_reversal_alpha_transfer=0.33,
                notes="Higher beta to global retail; use small weight with IBIT in risk-parity satellite.",
            ),
        }
    )
